<?php
/*
Description: Embed Analytics View Page
Version: 1.0.0
Author: Gregory Hoole <greg@ultimatenewmedia.com>
*/

require_once dirname(dirname(__FILE__)) . '/embed-analytics.php';

$e = new EmbedAnalytics(
    'testserviceaccount@feisty-tempest-122515.iam.gserviceaccount.com',
    dirname(dirname(__FILE__)) . '/cert/service-account.p12',
    'UA-58599001-1'
);
$e->initialize();

?>

<div class="wrap">

    <h1>Embed Analytics</h1>
    <div>
        <form id="embed-analytics" action="" method="get">
            <input type="hidden" name="page" value="embed_analytics" />
            <input type="text" name="date_range" value='<?php echo json_encode($date_range); ?>'/>
        </form>
    </div>
    <div class="section-container">
        <label>New Users</label>
        <section id="chart-1-container"></section>
    </div>

    <div class="section-container">
        <label>Sessions vs Users</label>
        <section id="chart-2-container"></section>
    </div>

    <div class="section-container">
        <label>Page Views per Session</label>
        <section id="chart-5-container"></section>
    </div>

    <div class="section-container">
        <label>Top 7 Pages</label>
        <section id="chart-3-container"></section>
    </div>

    <div class="section-container">
        <label>Top Countries by Sessions</label>
        <section id="chart-4-container"></section>
    </div>

    <div class="section-container">
        <label>Sessions by Source</label>
        <section id="chart-6-container"></section>
    </div>

</div>

<script>
(function(w,d,s,g,js,fjs){
  g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(cb){this.q.push(cb)}};
  js=d.createElement(s);fjs=d.getElementsByTagName(s)[0];
  js.src='https://apis.google.com/js/platform.js';
  fjs.parentNode.insertBefore(js,fjs);js.onload=function(){g.load('analytics')};
}(window,document,'script'));
</script>

<script>
gapi.analytics.ready(function() {

  var IDS = 'ga:<?php echo $e->get('profileId'); ?>';
  var ACCESS_TOKEN = '<?php echo $e->get('accessToken'); ?>';
  var START_DATE = '<?php echo $date_range['start']; ?>';
  var END_DATE = '<?php echo $date_range['end']; ?>';

  gapi.analytics.auth.authorize({
    serverAuth: {
      access_token: ACCESS_TOKEN
    }
  });

  var dataChart1 = new gapi.analytics.googleCharts.DataChart({
    reportType: 'ga',
    query: {
      'ids': IDS,
      'dimensions': 'ga:date',
      'metrics': 'ga:newUsers',
      'start-date': START_DATE,
      'end-date': END_DATE,
    },
    chart: {
      type: 'LINE',
      container: 'chart-1-container',
      'options': {
        'width': '100%'
      }
    }
  }).execute();

  var dataChart2 = new gapi.analytics.googleCharts.DataChart({
    query: {
      'ids': IDS,
      'start-date': START_DATE,
      'end-date': END_DATE,
      'metrics': 'ga:sessions,ga:users',
      'dimensions': 'ga:date'
    },
    chart: {
      'type': 'LINE',
      'container': 'chart-2-container',
      'options': {
        'width': '100%'
      }
    }
  }).execute();

  var dataChart3 = new gapi.analytics.googleCharts.DataChart({
    query: {
      'ids': IDS, 
      'start-date': START_DATE,
      'end-date': END_DATE,
      'metrics': 'ga:pageviews',
      'dimensions': 'ga:pagePathLevel1',
      'sort': '-ga:pageviews',
      'filters': 'ga:pagePathLevel1!=/',
      'max-results': 7
    },
    chart: {
      'type': 'PIE',
      'container': 'chart-3-container',
      'options': {
        'width': '100%',
        'pieHole': 4/9,
      }
    }
  }).execute();

  var dataChart4 = new gapi.analytics.googleCharts.DataChart({
    query: {
      'ids': IDS, 
      'metrics': 'ga:sessions',
      'dimensions': 'ga:country',
      'start-date': START_DATE,
      'end-date': END_DATE,
      'max-results': 6,
      sort: '-ga:sessions'
    },
    chart: {
      'type': 'PIE',
      'container': 'chart-4-container',
      'options': {
        'width': '100%',
        'pieHole': 4/9
      }
    }
  }).execute();

  var dataChart5 = new gapi.analytics.googleCharts.DataChart({
    reportType: 'ga',
    query: {
      'ids': IDS,
      'dimensions': 'ga:date',
      'metrics': 'ga:pageviewsPerSession',
      'start-date': START_DATE,
      'end-date': END_DATE,
    },
    chart: {
      type: 'LINE',
      container: 'chart-5-container',
      'options': {
        'width': '100%'
      }
    }
  }).execute();

  var dataChart6 = new gapi.analytics.googleCharts.DataChart({
    query: {
      'ids': IDS, 
      'metrics': 'ga:sessions',
      'dimensions': 'ga:source',
      'start-date': START_DATE,
      'end-date': END_DATE,
      'max-results': 6,
      sort: '-ga:sessions'
    },
    chart: {
      'type': 'PIE',
      'container': 'chart-6-container',
      'options': {
        'width': '100%',
        'pieHole': 4/9
      }
    }
  }).execute();

});
</script>