<?php
/*
Description: Embed Analytics View Page
Version: 1.0.0
Author: Gregory Hoole <greg@ultimatenewmedia.com>
*/

require_once dirname(dirname(__FILE__)) . '/embed-analytics.php';

$e = new EmbedAnalytics(
    'testserviceaccount@feisty-tempest-122515.iam.gserviceaccount.com',
    dirname(dirname(__FILE__)) . '/cert/service-account.p12',
    'UA-58599001-1'
);
$e->initialize();

?>


<div class="embed-wrap">

    <h1>Embed Analytics</h1>

    <div class="toolbar">
        <div id="active-users-container"></div>
        <form id="embed-analytics" action="" method="get">
            <input type="hidden" name="page" value="embed_analytics" />
            <input type="text" name="date_range" value='<?php echo json_encode($date_range); ?>'/>
        </form>
    </div>

    <h2>Website Traffic</h2>

    <div class="section-parent">

      <div class="section-container">
          <label>Sessions</label>
          <section id="traffic-1-container"></section>
      </div>

      <div class="section-container">
          <label>Pageviews</label>
          <section id="traffic-2-container"></section>
      </div>

      <div class="section-container">
          <label>Page Views per Session</label>
          <section id="traffic-3-container"></section>
      </div>

      <div class="section-container">
          <label>Users</label>
          <section id="traffic-4-container"></section>
      </div>

      <div class="section-container">
          <label>New Users</label>
          <section id="traffic-5-container"></section>
      </div>

      <div class="section-container">
          <label>Sessions vs Users</label>
          <section id="traffic-6-container"></section>
      </div>

    </div>

    <h2>Content Statistics</h2>

    <div class="section-parent">

      <div class="section-container">
          <label>Top Jobs | <a href="javascript:;" onclick="Embed.viewAll('6', 'Top Jobs');">View All</a></label>
          <section id="content-1-container"></section>
      </div>

      <div class="section-container">
          <label>Top Events | <a href="javascript:;" onclick="Embed.viewAll('7', 'Top Events');">View All</a></label>
          <section id="content-2-container"></section>
      </div>

      <div class="section-container">
          <label>Top Blogs | <a href="javascript:;" onclick="Embed.viewAll('8', 'Top Blogs');">View All</a></label>
          <section id="content-3-container"></section>
      </div>

      <div class="section-container">
          <label>Top Resources | <a href="javascript:;" onclick="Embed.viewAll('9', 'Top Resources');">View All</a></label>
          <section id="content-4-container"></section>
      </div>

      <div class="section-container">
          <label>Top Pages | <a href="javascript:;" onclick="Embed.viewAll('10', 'Top Pages');">View All</a></label>
          <section id="content-5-container"></section>
      </div>

      <div class="section-container">
          <label>Top Sources | <a href="javascript:;" onclick="Embed.viewAll('11', 'Top Sources');">View All</a></label>
          <section id="content-6-container"></section>
      </div>

    </div>

    <div id="view-all" class="section-parent">
        <h2></h2>
        <div id="view-all-chart"></div>
    </div>

</div>

<script>
(function(w,d,s,g,js,fjs){
  g=w.gapi||(w.gapi={});g.analytics={q:[],ready:function(cb){this.q.push(cb)}};
  js=d.createElement(s);fjs=d.getElementsByTagName(s)[0];
  js.src='https://apis.google.com/js/platform.js';
  fjs.parentNode.insertBefore(js,fjs);js.onload=function(){g.load('analytics')};
}(window,document,'script'));
</script>

<!-- Include the ActiveUsers component script. -->
<script src="<?php echo content_url(); ?>/lib/js/jquery-scrollto.js"></script>
<script src="<?php echo plugins_url('/js/active-users.js', dirname(__FILE__)); ?>"></script>

<script>
jQuery(function($){
  Embed.IDS = 'ga:<?php echo $e->get('profileId'); ?>';
  Embed.ACCESS_TOKEN = '<?php echo $e->get('accessToken'); ?>';
  Embed.START_DATE = '<?php echo $date_range['start']; ?>';
  Embed.END_DATE = '<?php echo $date_range['end']; ?>';
});
</script>